### ISSUE TITLE
Review of Bash section

### ISSUE THREAD

**Issue by jag1g13** [SABS-R3/software-engineering-day1#16]
- Says that Command Line Interface is commonly shortened to CLI, could do the same for GUI, so that's already familiar for later
- "provisioned laptop which use Ubuntu" -> uses
- "One key thing to remember is that the shell is always somewhere in your filesystem"
  - A little confusing - maybe something like "in the shell, you are always looking at somewhere in your filesystem"
  - Also, is 'filesystem' a familiar term to everyone?
- "We can move our working directory by using the cd (change directory) command,"
  - A bit confusing use of 'move' - maybe "change which directory we're looking at"
- Really like the comparison with the GUI view
- Says what pwd, cd and ls are abbreviations for, but not cp, mv and rm (though they're more obvious)

**Comment by steve-crouch** [comment]
Thanks @jag1g13, agree with all of these - I've worked these into the text. Could you do a quick verify/close?

**Comment by jag1g13** [comment]
Yep, looks good to me

**Comment by steve-crouch** [comment]
Thanks!
